ASM			:= C:/cygwin64/home/fbeth/opt/cross/bin/$(ISA)-elf-as
CC			:= C:/cygwin64/home/fbeth/opt/cross/bin/$(ISA)-elf-gcc
CPP			:= C:/cygwin64/home/fbeth/opt/cross/bin/$(ISA)-elf-g++
LD			:= C:/cygwin64/home/fbeth/opt/cross/bin/$(ISA)-elf-g++
OBJCOPY		:= C:/cygwin64/home/fbeth/opt/cross/bin/$(ISA)-elf-objcopy
GDB			:= C:/cygwin64/bin/gdb
FIND		:= C:/cygwin64/bin/find
EMU			:= C:/qemu/qemu-system-i386
GRUB		:= C:/grub/grub-mkrescue
CAT			:= type
DD			:= 
CP			:= cp
