/**
 * cpp/x86/crtn.s
 * 
 * '_init' and '_fini' provide the framework for the code generated by gcc responsible
 * for calling constructors/destructors of global objects etc.
**/

.section .init
	/* Content of .init in crtend.o */
	popl %ebp
	ret

.section .fini
	/* Content of .fini in crtend.o */
	popl %ebp
	ret
