#ifndef DANAOS_ARCH_I386_HAL_INTERRUPTS_ISR_COUNT_H_
#define DANAOS_ARCH_I386_HAL_INTERRUPTS_ISR_COUNT_H_

#include <stddef.h>

namespace hal {
	constexpr size_t ISR_COUNT = 256;
};

#endif //DANAOS_ARCH_I386_HAL_INTERRUPTS_ISR_COUNT_H_