/**
 * cpp/x86_64/crti.s
 * 
 * '_init' and '_fini' provide the framework for the code generated by gcc responsible
 * for calling constructors/destructors of global objects etc.
**/

.section .init
.global _init

.type _init, @function
.code64
_init:
	push %rbp
	movq %rsp, %rbp
	/* Content of .init in crtbegin.o */

.section .fini
.global _fini
.type _fini, @function
.code64
_fini:
	push %rbp
	movq %rsp, %rbp
	/* Content of .fini in crtbegin.o */
